version: '3.9'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: 'mydatabase'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'example'
    ports:
      - "27017:27017"
    volumes:
      - databaseDataa:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - app-network
    depends_on:
      - mongo
networks:
  app-network:
    driver: bridge
volumes:
  databaseDataa: