version: '3.9'
services:
  app:
    build: ./Docker
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: 'mydatabase'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./Docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - app-network
    depends_on:
      - mongo
networks:
  app-network:
    driver: bridge